// AUTO-GENERATED by scripts/measureXbotBones.mjs — do not edit by hand.
// Re-run the script if the base skeleton GLB changes.
//
// segmentLength: distance from this bone to its first child Mixamo bone, in the
// same units the GLB uses (xbot-walk.glb stores transforms in centimetres — Mixamo
// FBX default; Blender does not normalise units on export with export_apply=False).
// This matches bone.position.length() in Three.js exactly at runtime.

export interface BoneMeasurement {
  /** Distance from this bone to its first child Mixamo bone (GLB units = cm for xbot). */
  segmentLength: number;
}

export const XBOT_BONES: Record<string, BoneMeasurement> = {
  mixamorigHead: { segmentLength: 23.279 },
  mixamorigHips: { segmentLength: 10.1824 },
  mixamorigLeftArm: { segmentLength: 27.8415 },
  mixamorigLeftFoot: { segmentLength: 13.8169 },
  mixamorigLeftForeArm: { segmentLength: 28.3288 },
  mixamorigLeftHand: { segmentLength: 3.9696 },
  mixamorigLeftHandIndex1: { segmentLength: 3.7 },
  mixamorigLeftHandIndex2: { segmentLength: 2.85 },
  mixamorigLeftHandIndex3: { segmentLength: 2.7749 },
  mixamorigLeftHandMiddle1: { segmentLength: 3.7 },
  mixamorigLeftHandMiddle2: { segmentLength: 2.95 },
  mixamorigLeftHandMiddle3: { segmentLength: 2.9529 },
  mixamorigLeftHandPinky1: { segmentLength: 3.6 },
  mixamorigLeftHandPinky2: { segmentLength: 2.1 },
  mixamorigLeftHandPinky3: { segmentLength: 2.1255 },
  mixamorigLeftHandRing1: { segmentLength: 3.15 },
  mixamorigLeftHandRing2: { segmentLength: 2.95 },
  mixamorigLeftHandRing3: { segmentLength: 2.6443 },
  mixamorigLeftHandThumb1: { segmentLength: 4.1871 },
  mixamorigLeftHandThumb2: { segmentLength: 3.4184 },
  mixamorigLeftHandThumb3: { segmentLength: 2.5806 },
  mixamorigLeftLeg: { segmentLength: 44.5279 },
  mixamorigLeftShoulder: { segmentLength: 10.8377 },
  mixamorigLeftToeBase: { segmentLength: 9.2781 },
  mixamorigLeftUpLeg: { segmentLength: 44.3714 },
  mixamorigNeck: { segmentLength: 9.7643 },
  mixamorigRightArm: { segmentLength: 27.8415 },
  mixamorigRightFoot: { segmentLength: 13.8169 },
  mixamorigRightForeArm: { segmentLength: 28.3288 },
  mixamorigRightHand: { segmentLength: 3.968 },
  mixamorigRightHandIndex1: { segmentLength: 3.7 },
  mixamorigRightHandIndex2: { segmentLength: 2.85 },
  mixamorigRightHandIndex3: { segmentLength: 2.7722 },
  mixamorigRightHandMiddle1: { segmentLength: 3.7 },
  mixamorigRightHandMiddle2: { segmentLength: 2.95 },
  mixamorigRightHandMiddle3: { segmentLength: 2.9466 },
  mixamorigRightHandPinky1: { segmentLength: 3.6 },
  mixamorigRightHandPinky2: { segmentLength: 2.1 },
  mixamorigRightHandPinky3: { segmentLength: 2.1158 },
  mixamorigRightHandRing1: { segmentLength: 3.3793 },
  mixamorigRightHandRing2: { segmentLength: 2.8897 },
  mixamorigRightHandRing3: { segmentLength: 2.6388 },
  mixamorigRightHandThumb1: { segmentLength: 4.189 },
  mixamorigRightHandThumb2: { segmentLength: 3.4163 },
  mixamorigRightHandThumb3: { segmentLength: 2.575 },
  mixamorigRightLeg: { segmentLength: 44.5278 },
  mixamorigRightShoulder: { segmentLength: 10.8382 },
  mixamorigRightToeBase: { segmentLength: 9.2781 },
  mixamorigRightUpLeg: { segmentLength: 44.3715 },
  mixamorigSpine: { segmentLength: 10.0027 },
  mixamorigSpine1: { segmentLength: 9.3221 },
  mixamorigSpine2: { segmentLength: 16.8653 },
};
