/**
 * Reads xbot-walk.glb, parses the GLTF JSON chunk, and outputs a TypeScript
 * constant file with every Mixamo bone's segment length (distance from the bone
 * to its first child, i.e. bone.position.length() in Three.js local space).
 *
 * Usage:
 *   node scripts/measureXbotBones.mjs
 *
 * Writes: src/core/character/xbotSkeleton.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GLB_PATH = path.join(__dirname, '../static/models/gltf/xbot-walk.glb');
const OUT_PATH = path.join(__dirname, '../src/core/character/xbotSkeleton.ts');

// --- Parse GLB binary ---
const buf = fs.readFileSync(GLB_PATH);
const magic = buf.readUInt32LE(0);
if (magic !== 0x46546C67) throw new Error('Not a valid GLB file');

const jsonChunkLen = buf.readUInt32LE(12);
const jsonChunkType = buf.readUInt32LE(16);
if (jsonChunkType !== 0x4E4F534A) throw new Error('First chunk is not JSON');

const json = JSON.parse(buf.slice(20, 20 + jsonChunkLen).toString('utf8'));

// --- Build node map ---
const nodes = json.nodes || [];

// Map node index → { name, translation, children }
// GLTF node translation = local position relative to parent
const nodeMap = nodes.map((n, i) => ({
  index: i,
  name: n.name || '',
  // translation is [x, y, z] local offset from parent; defaults to [0,0,0]
  translation: n.translation ? [...n.translation] : [0, 0, 0],
  children: n.children || [],
}));

// Build parent lookup
const parentOf = new Array(nodes.length).fill(-1);
for (const node of nodeMap) {
  for (const childIdx of node.children) {
    parentOf[childIdx] = node.index;
  }
}

// --- Collect Mixamo bones ---
// Strip colon from raw GLTF names (e.g. "mixamorig:Head" → "mixamorigHead")
// to match the names Three.js GLTFLoader produces.
function normaliseName(raw) {
  return raw.replace('mixamorig:', 'mixamorig');
}

// Segment length = distance from bone to its first child (bone.position.length() in Three.js)
// That equals the magnitude of the child's local translation.
const segmentLengths = {};

for (const node of nodeMap) {
  if (!node.name.startsWith('mixamorig')) continue;

  for (const childIdx of node.children) {
    const child = nodeMap[childIdx];
    if (!child.name.startsWith('mixamorig')) continue;

    const [x, y, z] = child.translation;
    const len = Math.sqrt(x * x + y * y + z * z);

    const normParent = normaliseName(node.name);
    // Store: for this bone, what is the distance to its child?
    // (If multiple children, take the first mixamorig child — matches Three.js behaviour.)
    if (!(normParent in segmentLengths)) {
      segmentLengths[normParent] = Math.round(len * 10000) / 10000;
    }
  }
}

// Also record the leaf bone distances (HeadTop_End, finger tips, toe tips)
// as "childLength" from their parent — useful for sphere sizing.
const childLengths = {};
for (const node of nodeMap) {
  if (!node.name.startsWith('mixamorig')) continue;
  const parentIdx = parentOf[node.index];
  if (parentIdx < 0) continue;
  const parent = nodeMap[parentIdx];
  if (!parent.name.startsWith('mixamorig')) continue;

  const [x, y, z] = node.translation;
  const len = Math.sqrt(x * x + y * y + z * z);
  childLengths[normaliseName(node.name)] = Math.round(len * 10000) / 10000;
}

// --- Sort and report ---
const sorted = Object.entries(segmentLengths).sort(([a], [b]) => a.localeCompare(b));

console.log(`Parsed ${nodes.length} nodes from ${path.basename(GLB_PATH)}`);
console.log(`Found ${sorted.length} Mixamo bones with segment lengths:\n`);
console.table(Object.fromEntries(sorted.map(([k, v]) => [k, { segmentLength_m: v }])));

// --- Write TypeScript output ---
const lines = [
  '// AUTO-GENERATED by scripts/measureXbotBones.mjs — do not edit by hand.',
  '// Re-run the script if the base skeleton GLB changes.',
  '//',
  '// segmentLength: distance from bone to its first Mixamo child bone (metres).',
  '// This equals bone.position.length() in Three.js after GLTFLoader normalises',
  '// bone names (strips the "mixamorig:" colon).',
  '',
  'export interface BoneMeasurement {',
  '  /** Distance from this bone to its first child Mixamo bone (metres). */',
  '  segmentLength: number;',
  '}',
  '',
  'export const XBOT_BONES: Record<string, BoneMeasurement> = {',
];

for (const [name, len] of sorted) {
  lines.push(`  ${name}: { segmentLength: ${len} },`);
}

lines.push('};', '');

fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
console.log(`\nWrote ${OUT_PATH}`);
